.TH "Minishelln/include Directory Reference" 3 "Version 1.0" "Alizée et Vladimir minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Minishelln/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbuiltins\&.h\fP"
.br
.ti -1c
.RI "file \fBexecutor\&.h\fP"
.br
.ti -1c
.RI "file \fBhistory\&.h\fP"
.br
.ti -1c
.RI "file \fBparser\&.h\fP"
.br
.ti -1c
.RI "file \fBtypedef\&.h\fP"
.br
.in -1c
