.TH "Alias" 3 "Version 1.0" "shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alias \- Structure représentant un alias\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <typedef\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBalias\fP"
.br
.ti -1c
.RI "char * \fBcommand\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure représentant un alias\&. 
.PP
Definition at line \fB34\fP of file \fBtypedef\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char* Alias::alias"

.PP
Definition at line \fB35\fP of file \fBtypedef\&.h\fP\&.
.SS "char* Alias::command"

.PP
Definition at line \fB36\fP of file \fBtypedef\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for shell from the source code\&.
