.TH "Minishelln/src/builtins.c" 3 "Version 1.0" "Alizée et Vladimir minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Minishelln/src/builtins.c
.SH SYNOPSIS
.br
.PP
\fC#include 'include/typedef\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBbuiltin_cd\fP (char **args)"
.br
.RI "Change le répertoire courant\&. "
.ti -1c
.RI "int \fBbuiltin_pwd\fP ()"
.br
.RI "Affiche le répertoire courant\&. "
.ti -1c
.RI "int \fBbuiltin_echo\fP (char **args)"
.br
.RI "Affiche l'argument passé en paramètre\&. "
.ti -1c
.RI "int \fBbuiltin_exit\fP ()"
.br
.RI "Sortir du shell\&. "
.ti -1c
.RI "int \fBfind_env_var\fP (const char *name)"
.br
.RI "Affiche la liste des variables d'environnement\&. "
.ti -1c
.RI "void \fBset_env_var\fP (const char *name, const char *value)"
.br
.RI "Change la valeur d'une variable d'environnement\&. "
.ti -1c
.RI "char * \fBget_env_var\fP (const char *name)"
.br
.RI "Récupère la valeur d'une variable d'environnement\&. "
.ti -1c
.RI "void \fBunset_env_var\fP (const char *name)"
.br
.RI "Supprime une variable d'environnement\&. "
.ti -1c
.RI "void \fBexpand_env_variables\fP (char **args)"
.br
.RI "Attribution de la variable d'environnement\&. "
.ti -1c
.RI "int \fBbuiltin_env\fP ()"
.br
.RI "Affiche la liste des variables d'environnement\&. "
.ti -1c
.RI "void \fBset_alias\fP (const char *alias, const char *command)"
.br
.RI "Change la valeur d'un alias\&. "
.ti -1c
.RI "char * \fBget_alias\fP (const char *alias)"
.br
.RI "Récupère la valeur d'un alias\&. "
.ti -1c
.RI "void \fBunset_alias\fP (const char *alias)"
.br
.RI "Supprime un alias\&. "
.ti -1c
.RI "int \fBbuiltin_alias\fP ()"
.br
.RI "Affiche la liste des alias\&. "
.ti -1c
.RI "void \fBexpand_alias\fP (char **args)"
.br
.RI "Attribution de l'alias\&. "
.ti -1c
.RI "int \fBis_builtin\fP (char **args)"
.br
.RI "Vérifie si la commande est un built-in\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBEnvVar\fP \fBenv_vars\fP [\fBMAX_ENV_VARS\fP]"
.br
.ti -1c
.RI "int \fBenv_count\fP = 0"
.br
.ti -1c
.RI "\fBAlias\fP \fBaliases\fP [\fBMAX_ALIASES\fP]"
.br
.ti -1c
.RI "int \fBalias_count\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int builtin_alias ()"

.PP
Affiche la liste des alias\&. 
.PP
\fBReturns\fP
.RS 4
0 si réussi, -1 si une erreur est survenue\&. 
.RE
.PP

.PP
Definition at line \fB245\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
245                     {
246     for (int i = 0; i < alias_count; i++) {
247         printf("alias %s='%s'\\n", aliases[i]\&.alias, aliases[i]\&.command);
248     }
249     if (alias_count == 0) {
250         printf("No aliases defined\&.\\n");
251     }
252     return 0;
253 }
.fi

.SS "int builtin_cd (char ** args)"

.PP
Change le répertoire courant\&. 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Liste des arguments\&. args[1] doit être le répertoire cible\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 si réussi, -1 si une erreur est survenue\&. 
.RE
.PP

.PP
Definition at line \fB9\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
9                             {
10     if (!args) {
11         errno = EFAULT;
12         return \-1;
13     }
14 
15     if (!args[1]) {
16         perror("cd: missing argument\\n");
17         return \-1;
18     }
19     if (chdir(args[1]) != 0) {
20         switch (errno) {
21             case EFAULT: perror("cd: Bad address\\n"); break;
22             case ENOTDIR: perror("cd: Not a directory\\n"); break;
23             case ELOOP: perror("cd: Too many symbolic links\\n"); break;
24             default: perror("cd"); break;
25         }
26         return \-1;
27     }
28     return 0;
29 }
.fi

.SS "int builtin_echo (char ** args)"

.PP
Affiche l'argument passé en paramètre\&. 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Liste des arguments\&. args[1] doit être le texte à afficher\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 si réussi, -1 si une erreur est survenue\&. 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
45                               {
46     if (!args) {
47         errno = EFAULT;
48         return \-1;
49     }
50 
51     for (int i = 1; args[i]; i++) {
52         if (args[i][0] == '"' && args[i][strlen(args[i]) \- 1] == '"') {
53             args[i][strlen(args[i]) \- 1] = '\\0';
54             printf("%s", args[i] + 1);
55         } else {
56             printf("%s", args[i]);
57         }
58         if (args[i + 1]) {
59             printf(" ");
60         }
61     }
62     printf("\\n");
63     return 0;
64 }
.fi

.SS "int builtin_env ()"

.PP
Affiche la liste des variables d'environnement\&. 
.PP
\fBReturns\fP
.RS 4
0 si réussi, -1 si une erreur est survenue\&. 
.RE
.PP

.PP
Definition at line \fB164\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
164                   {
165     for (int i = 0; i < env_count; i++) {
166         printf("%s=%s\\n", env_vars[i]\&.name, env_vars[i]\&.value);
167     }
168     if (env_count == 0) {
169         printf("No environment variables defined\&.\\n");
170     }
171     return 0;
172 }
.fi

.SS "int builtin_exit ()"

.PP
Sortir du shell\&. 
.PP
\fBReturns\fP
.RS 4
0 si réussi, -1 si une erreur est survenue\&. 
.RE
.PP

.PP
Definition at line \fB66\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
66                    {
67     printf("Exiting shell\&.\&.\&.\\nThanks to have used it ! Bye !\\n");
68     exit(0);
69 }
.fi

.SS "int builtin_pwd ()"

.PP
Affiche le répertoire courant\&. 
.PP
\fBReturns\fP
.RS 4
0 si réussi, -1 si une erreur est survenue\&. 
.RE
.PP

.PP
Definition at line \fB31\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
31                   {
32     char cwd[1024];
33     if (getcwd(cwd, sizeof(cwd)) == NULL) {
34         switch (errno) {
35             case EFAULT: perror("pwd: Bad address\\n"); break;
36             case ERANGE: perror("pwd: Buffer too small\\n"); break;
37             default: perror("pwd"); break;
38         }
39         return \-1;
40     }
41     printf("%s\\n", cwd);
42     return 0;
43 }
.fi

.SS "void expand_alias (char ** args)"

.PP
Attribution de l'alias\&. 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Liste des arguments\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 si réussi, -1 si une erreur est survenue\&. 
.RE
.PP

.PP
Definition at line \fB255\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
255                                {
256     if (!args) {
257         errno = EFAULT;
258         return;
259     }
260 
261     if (args[0] == NULL) return;
262 
263     char *alias_value = get_alias(args[0]);
264     if (alias_value) {
265         char *alias_copy = strdup(alias_value);
266         int i = 0;
267         char *token = strtok(alias_copy, " ");
268         while (token && i < MAX_ARGS \- 1) {
269             args[i++] = strdup(token);
270             token = strtok(NULL, " ");
271         }
272         args[i] = NULL;
273         free(alias_copy);
274     }
275 }
.fi

.SS "void expand_env_variables (char ** args)"

.PP
Attribution de la variable d'environnement\&. 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Liste des arguments\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 si réussi, -1 si une erreur est survenue\&. 
.RE
.PP

.PP
Definition at line \fB143\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
143                                        {
144     if (!args) {
145         errno = EFAULT;
146         return;
147     }
148 
149     for (int i = 0; args[i]; i++) {
150         if (args[i][0] == '$' && strlen(args[i]) > 1) {
151             char *var_name = args[i] + 1;
152             char *value = get_env_var(var_name);
153             if (value) {
154                 free(args[i]);
155                 if ((args[i] = strdup(value)) == NULL) {
156                     perror("expand_env_variables: Memory allocation failed\\n");
157                     exit(EXIT_FAILURE);
158                 }
159             }
160         }
161     }
162 }
.fi

.SS "int find_env_var (const char * name)"

.PP
Affiche la liste des variables d'environnement\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP Nom de la variable d'environnement à chercher\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 si réussi, -1 si une erreur est survenue\&. 
.RE
.PP

.PP
Definition at line \fB75\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
75                                    {
76     if (!name) {
77         errno = EFAULT;
78         return \-1;
79     }
80 
81     for (int i = 0; i < env_count; i++) {
82         if (strcmp(env_vars[i]\&.name, name) == 0) {
83             return i;
84         }
85     }
86     return \-1;
87 }
.fi

.SS "char * get_alias (const char * alias)"

.PP
Récupère la valeur d'un alias\&. 
.PP
\fBParameters\fP
.RS 4
\fIalias\fP Nom de l'alias\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Commande associée à l'alias\&. 
.RE
.PP

.PP
Definition at line \fB212\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
212                                    {
213     if (!alias) {
214         errno = EFAULT;
215         return NULL;
216     }
217 
218     for (int i = 0; i < alias_count; i++) {
219         if (strcmp(aliases[i]\&.alias, alias) == 0) {
220             return aliases[i]\&.command;
221         }
222     }
223     return NULL;
224 }
.fi

.SS "char * get_env_var (const char * name)"

.PP
Récupère la valeur d'une variable d'environnement\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP Nom de la variable d'environnement\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Valeur de la variable d'environnement\&. 
.RE
.PP

.PP
Definition at line \fB116\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
116                                     {
117     if (!name) {
118         errno = EFAULT;
119         return NULL;
120     }
121 
122     int index = find_env_var(name);
123     return index >= 0 ? env_vars[index]\&.value : NULL;
124 }
.fi

.SS "int is_builtin (char ** args)"

.PP
Vérifie si la commande est un built-in\&. 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Liste des arguments\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 si la commande est un built-in, -1 sinon\&. 
.RE
.PP

.PP
Definition at line \fB277\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
277                             {
278     if (!args || !args[0]) {
279         errno = EFAULT;
280         return \-1;
281     }
282 
283     if (strcmp(args[0], "cd") == 0) return builtin_cd(args);
284     if (strcmp(args[0], "pwd") == 0) return builtin_pwd();
285     if (strcmp(args[0], "exit") == 0) return builtin_exit();
286     if (strcmp(args[0], "echo") == 0) return builtin_echo(args);
287     if (strcmp(args[0], "env") == 0) return builtin_env();
288     if (strcmp(args[0], "aliases") == 0) return builtin_alias();
289 
290     return \-1; // Pas de commande built\-in
291 }
.fi

.SS "void set_alias (const char * alias, const char * command)"

.PP
Change la valeur d'un alias\&. 
.PP
\fBParameters\fP
.RS 4
\fIalias\fP Nom de l'alias\&. 
.br
\fIcommand\fP Commande associée à l'alias\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 si réussi, -1 si une erreur est survenue\&. 
.RE
.PP

.PP
Definition at line \fB178\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
178                                                        {
179     if (!alias || !command) {
180         errno = EFAULT;
181         return;
182     }
183 
184     if (strcmp(alias, command) == 0) {
185         perror("alias: cannot create recursive alias\\n");
186         return;
187     }
188 
189     for (int i = 0; i < alias_count; i++) {
190         if (strcmp(aliases[i]\&.alias, alias) == 0) {
191             free(aliases[i]\&.command);
192             if ((aliases[i]\&.command = strdup(command)) == NULL) {
193                 perror("set_alias: Memory allocation failed\\n");
194                 exit(EXIT_FAILURE);
195             }
196             return;
197         }
198     }
199 
200     if (alias_count < MAX_ALIASES) {
201         if ((aliases[alias_count]\&.alias = strdup(alias)) == NULL ||
202             (aliases[alias_count]\&.command = strdup(command)) == NULL) {
203             perror("set_alias: Memory allocation failed\\n");
204             exit(EXIT_FAILURE);
205         }
206         alias_count++;
207     } else {
208         perror("Maximum alias limit reached\&.\\n");
209     }
210 }
.fi

.SS "void set_env_var (const char * name, const char * value)"

.PP
Change la valeur d'une variable d'environnement\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP Nom de la variable d'environnement\&. 
.br
\fIvalue\fP Valeur de la variable d'environnement\&. 
.RE
.PP

.PP
Definition at line \fB89\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
89                                                       {
90     if (!name || !value) {
91         errno = EFAULT;
92         return;
93     }
94 
95     int index = find_env_var(name);
96     if (index >= 0) {
97         free(env_vars[index]\&.value);
98         if ((env_vars[index]\&.value = strdup(value)) == NULL) {
99             perror("set_env_var: Memory allocation failed\\n");
100             exit(EXIT_FAILURE);
101         }
102     } else {
103         if (env_count < MAX_ENV_VARS) {
104             if ((env_vars[env_count]\&.name = strdup(name)) == NULL ||
105                 (env_vars[env_count]\&.value = strdup(value)) == NULL) {
106                 perror("set_env_var: Memory allocation failed\\n");
107                 exit(EXIT_FAILURE);
108             }
109             env_count++;
110         } else {
111             perror("Maximum environment variable limit reached\&.\\n");
112         }
113     }
114 }
.fi

.SS "void unset_alias (const char * alias)"

.PP
Supprime un alias\&. 
.PP
\fBParameters\fP
.RS 4
\fIalias\fP Nom de l'alias\&. 
.RE
.PP

.PP
Definition at line \fB226\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
226                                     {
227     if (!alias) {
228         errno = EFAULT;
229         return;
230     }
231 
232     for (int i = 0; i < alias_count; i++) {
233         if (strcmp(aliases[i]\&.alias, alias) == 0) {
234             free(aliases[i]\&.alias);
235             free(aliases[i]\&.command);
236             for (int j = i; j < alias_count \- 1; j++) {
237                 aliases[j] = aliases[j + 1];
238             }
239             alias_count\-\-;
240             return;
241         }
242     }
243 }
.fi

.SS "void unset_env_var (const char * name)"

.PP
Supprime une variable d'environnement\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP Nom de la variable d'environnement\&. 
.RE
.PP

.PP
Definition at line \fB126\fP of file \fBbuiltins\&.c\fP\&..PP
.nf
126                                      {
127     if (!name) {
128         errno = EFAULT;
129         return;
130     }
131 
132     int index = find_env_var(name);
133     if (index >= 0) {
134         free(env_vars[index]\&.name);
135         free(env_vars[index]\&.value);
136         for (int i = index; i < env_count \- 1; i++) {
137             env_vars[i] = env_vars[i + 1];
138         }
139         env_count\-\-;
140     }
141 }
.fi

.SH "Variable Documentation"
.PP 
.SS "int alias_count = 0"

.PP
Definition at line \fB176\fP of file \fBbuiltins\&.c\fP\&.
.SS "\fBAlias\fP aliases[\fBMAX_ALIASES\fP]"

.PP
Definition at line \fB175\fP of file \fBbuiltins\&.c\fP\&.
.SS "int env_count = 0"

.PP
Definition at line \fB73\fP of file \fBbuiltins\&.c\fP\&.
.SS "\fBEnvVar\fP env_vars[\fBMAX_ENV_VARS\fP]"

.PP
Definition at line \fB72\fP of file \fBbuiltins\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Alizée et Vladimir minishell from the source code\&.
