.TH "CommandNode" 3 "Version 1.0" "shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandNode \- Structure représentant un noeud de commande\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <typedef\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBcommand\fP"
.br
.ti -1c
.RI "\fBCommandType\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure représentant un noeud de commande\&. 
.PP
Definition at line \fB18\fP of file \fBtypedef\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char* CommandNode::command"

.PP
Definition at line \fB19\fP of file \fBtypedef\&.h\fP\&.
.SS "\fBCommandType\fP CommandNode::type"

.PP
Definition at line \fB20\fP of file \fBtypedef\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for shell from the source code\&.
