.TH "EnvVar" 3 "Version 1.0" "shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnvVar \- Structure représentant une variable d'environnement\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <typedef\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure représentant une variable d'environnement\&. 
.PP
Definition at line \fB26\fP of file \fBtypedef\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char* EnvVar::name"

.PP
Definition at line \fB27\fP of file \fBtypedef\&.h\fP\&.
.SS "char* EnvVar::value"

.PP
Definition at line \fB28\fP of file \fBtypedef\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for shell from the source code\&.
