.TH "Minishelln/src/executor.c" 3 "Version 1.0" "shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Minishelln/src/executor.c
.SH SYNOPSIS
.br
.PP
\fC#include 'include/builtins\&.h'\fP
.br
\fC#include 'include/parser\&.h'\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBopen_output_redirection\fP (const char *filename, int append)"
.br
.RI "Ouvre un fichier pour la redirection de la sortie standard\&. "
.ti -1c
.RI "int \fBopen_input_redirection\fP (const char *filename)"
.br
.RI "Ouvre un fichier pour la redirection de l'entrée standard\&. "
.ti -1c
.RI "void \fBhandle_redirections\fP (char **args, int *fd_in, int *fd_out)"
.br
.RI "Gère les redirections d'entrée et de sortie\&. "
.ti -1c
.RI "void \fBexecute_command\fP (char **args)"
.br
.RI "Exécute une commande\&. "
.ti -1c
.RI "int \fBcontains_redirection\fP (char **args)"
.br
.RI "Vérifie si une commande contient des opérateurs de redirection\&. "
.ti -1c
.RI "int \fBexecute_logic_command\fP (const char *command)"
.br
.RI "Exécute une commande logique\&. "
.ti -1c
.RI "void \fBexecute_piped_commands\fP (char **commands)"
.br
.RI "Exécute une commande avec des opérateurs de contrôle (pipe, redirection, etc\&.)\&. "
.ti -1c
.RI "int \fBcheck_background_execution\fP (char *command)"
.br
.RI "Vérifie si une commande nécessite une exécution en arrière-plan\&. "
.ti -1c
.RI "void \fBexecute_commands_with_logic\fP (const char *input)"
.br
.RI "Exécute des commandes avec des opérateurs logiques (&&, ||)\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int check_background_execution (char * command)"

.PP
Vérifie si une commande nécessite une exécution en arrière-plan\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP Commande à vérifier\&. 
.RE
.PP
\fBReturns\fP
.RS 4
1 si la commande nécessite une exécution en arrière-plan, 0 sinon\&. 
.RE
.PP

.PP
Definition at line \fB190\fP of file \fBexecutor\&.c\fP\&..PP
.nf
190                                               {
191     if (!command) {
192         errno = EFAULT;
193         return \-1;
194     }
195 
196     size_t len = strlen(command);
197     while (len > 0 && isspace(command[len \- 1])) {
198         command[\-\-len] = '\\0';
199     }
200     if (len > 0 && command[len \- 1] == '&') {
201         command[len \- 1] = '\\0';
202         return 1;
203     }
204     return 0;
205 }
.fi

.SS "int contains_redirection (char ** args)"

.PP
Vérifie si une commande contient des opérateurs de redirection\&. 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Tableau d'arguments de la commande\&. 
.RE
.PP
\fBReturns\fP
.RS 4
1 si la commande contient des opérateurs de redirection, 0 sinon\&. 
.RE
.PP

.PP
Definition at line \fB103\fP of file \fBexecutor\&.c\fP\&..PP
.nf
103                                       {
104     if (!args) {
105         errno = EFAULT;
106         return \-1;
107     }
108 
109     for (int i = 0; args[i]; i++) {
110         if (strcmp(args[i], ">") == 0 || strcmp(args[i], ">>") == 0 || strcmp(args[i], "<") == 0) {
111             return 1;
112         }
113     }
114     return 0;
115 }
.fi

.SS "void execute_command (char ** args)"

.PP
Exécute une commande\&. 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Tableau d'arguments de la commande\&. 
.RE
.PP

.PP
Definition at line \fB63\fP of file \fBexecutor\&.c\fP\&..PP
.nf
63                                   {
64     if (!args) {
65         errno = EFAULT;
66         return;
67     }
68 
69     expand_alias(args);
70 
71     int fd_out = \-1, fd_in = \-1;
72     int background = is_background_command(args);
73 
74     handle_redirections(args, &fd_in, &fd_out);
75 
76     pid_t pid = fork();
77     if (pid < 0) {
78         return;
79     }
80 
81     if (pid == 0) {  // Enfant
82         if (fd_out != \-1) {
83             dup2(fd_out, STDOUT_FILENO);
84             close(fd_out);
85         }
86         if (fd_in != \-1) {
87             dup2(fd_in, STDIN_FILENO);
88             close(fd_in);
89         }
90         execvp(args[0], args);
91         exit(EXIT_FAILURE);
92     } else {  // Parent
93         if (!background) {
94             int status;
95             waitpid(pid, &status, 0);
96         } else {
97             printf("[Background process started] PID: %d\\n", pid);
98         }
99     }
100 }
.fi

.SS "void execute_commands_with_logic (const char * input)"

.PP
Exécute des commandes avec des opérateurs logiques (&&, ||)\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP Commandes à exécuter\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 si la commande a été exécutée, -1 sinon\&. 
.RE
.PP

.PP
Definition at line \fB208\fP of file \fBexecutor\&.c\fP\&..PP
.nf
208                                                     {
209     if (!input) {
210         errno = EFAULT;
211         return;
212     }
213 
214     CommandNode commands[MAX_COMMANDS];
215     int command_count = parse_control_operators(input, commands);
216     int success = 1;
217 
218     for (int i = 0; i < command_count; i++) {
219         if (i > 0) {
220             if ((commands[i \- 1]\&.type == CMD_AND && !success) ||
221                 (commands[i \- 1]\&.type == CMD_OR && success)) {
222                 continue;
223             }
224         }
225 
226         char **args = parse_command(commands[i]\&.command);
227         if (!args) {
228             errno = ENOMEM;
229             return;
230         }
231 
232         if (contains_redirection(args)) {
233             execute_command(args);
234             success = 1;
235         } else if (args[0] != NULL) {
236             expand_env_variables(args);
237             int builtin_status = is_builtin(args);
238             if (builtin_status == 0) {
239                 success = 1;
240             } else {
241                 success = execute_logic_command(commands[i]\&.command) == 0;
242             }
243         }
244 
245         free(args);
246         free(commands[i]\&.command);
247     }
248 }
.fi

.SS "int execute_logic_command (const char * command)"

.PP
Exécute une commande logique\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP Commande à exécuter\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 si la commande a été exécutée, -1 sinon\&. 
.RE
.PP

.PP
Definition at line \fB118\fP of file \fBexecutor\&.c\fP\&..PP
.nf
118                                                {
119     if (!command) {
120         errno = EFAULT;
121         return \-1;
122     }
123 
124     pid_t pid = fork();
125     if (pid < 0) {
126         return \-1;
127     }
128     if (pid == 0) {
129         execlp("/bin/sh", "sh", "\-c", command, (char *)NULL);
130         exit(EXIT_FAILURE);
131     }
132     
133     int status;
134     waitpid(pid, &status, 0);
135     return WIFEXITED(status) ? WEXITSTATUS(status) : \-1;
136 }
.fi

.SS "void execute_piped_commands (char ** commands)"

.PP
Exécute une commande avec des opérateurs de contrôle (pipe, redirection, etc\&.)\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommands\fP Tableau de commandes et opérateurs de contrôle\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 si la commande a été exécutée, -1 sinon\&. 
.RE
.PP

.PP
Definition at line \fB139\fP of file \fBexecutor\&.c\fP\&..PP
.nf
139                                              {
140     if (!commands) {
141         errno = EFAULT;
142         return;
143     }
144 
145     int pipefd[2];
146     pid_t pid;
147     int fd_in = 0;
148 
149     for (int i = 0; commands[i] != NULL; i++) {
150         if (pipe(pipefd) == \-1) {
151             return;
152         }
153 
154         pid = fork();
155         if (pid == \-1) {
156             return;
157         }
158 
159         if (pid == 0) {
160             char **args = parse_command(commands[i]);
161             if (!args) {
162                 errno = ENOMEM;
163                 exit(EXIT_FAILURE);
164             }
165             int fd_out = \-1;
166             handle_redirections(args, &fd_in, &fd_out);
167 
168             dup2(fd_in, STDIN_FILENO);
169             if (commands[i + 1] != NULL) {
170                 dup2(pipefd[1], STDOUT_FILENO);
171             } else if (fd_out != \-1) {
172                 dup2(fd_out, STDOUT_FILENO);
173             }
174 
175             close(pipefd[0]);
176             close(pipefd[1]);
177 
178             execvp(args[0], args);
179             exit(EXIT_FAILURE);
180         } else {
181             waitpid(pid, NULL, 0);
182             close(pipefd[1]);
183             fd_in = pipefd[0];
184         }
185     }
186     close(fd_in);
187 }
.fi

.SS "void handle_redirections (char ** args, int * fd_in, int * fd_out)"

.PP
Gère les redirections d'entrée et de sortie\&. 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Tableau d'arguments de la commande\&. 
.br
\fIfd_in\fP Descripteur de fichier de l'entrée standard\&. 
.br
\fIfd_out\fP Descripteur de fichier de la sortie standard\&. 
.RE
.PP

.PP
Definition at line \fB41\fP of file \fBexecutor\&.c\fP\&..PP
.nf
41                                                                {
42     if (!args || !fd_in || !fd_out) {
43         errno = EFAULT;
44         return;
45     }
46     
47     for (int i = 0; args[i]; i++) {
48         if (strcmp(args[i], ">") == 0 || strcmp(args[i], ">>") == 0) {
49             *fd_out = open_output_redirection(args[i + 1], strcmp(args[i], ">>") == 0);
50             if (*fd_out == \-1) return;
51             args[i] = NULL;
52             break;
53         } else if (strcmp(args[i], "<") == 0) {
54             *fd_in = open_input_redirection(args[i + 1]);
55             if (*fd_in == \-1) return;
56             args[i] = NULL;
57             break;
58         }
59     }
60 }
.fi

.SS "int open_input_redirection (const char * filename)"

.PP
Ouvre un fichier pour la redirection de l'entrée standard\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Nom du fichier\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Descripteur de fichier du fichier ouvert\&. 
.RE
.PP

.PP
Definition at line \fB28\fP of file \fBexecutor\&.c\fP\&..PP
.nf
28                                                  {
29     if (!filename) {
30         errno = EFAULT;
31         return \-1;
32     }
33     
34     int fd = open(filename, O_RDONLY);
35     if (fd == \-1) {
36         return \-1;
37     }
38     return fd;
39 }
.fi

.SS "int open_output_redirection (const char * filename, int append)"

.PP
Ouvre un fichier pour la redirection de la sortie standard\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Nom du fichier\&. 
.br
\fIappend\fP 1 pour ajouter à la fin du fichier, 0 pour écraser le fichier\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Descripteur de fichier du fichier ouvert\&. 
.RE
.PP

.PP
Definition at line \fB14\fP of file \fBexecutor\&.c\fP\&..PP
.nf
14                                                               {
15     if (!filename) {
16         errno = EFAULT;
17         return \-1;
18     }
19 
20     int flags = O_WRONLY | O_CREAT | (append ? O_APPEND : O_TRUNC);
21     int fd = open(filename, flags, 0644);
22     if (fd == \-1) {
23         return \-1;
24     }
25     return fd;
26 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for shell from the source code\&.
