.TH "Minishelln/src/history.c" 3 "Version 1.0" "Alizée et Vladimir minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Minishelln/src/history.c
.SH SYNOPSIS
.br
.PP
\fC#include 'include/history\&.h'\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHISTORY_FILE\fP   'history\&.txt'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBadd_to_history\fP (const char *command)"
.br
.RI "Ajoute une commande à l'historique\&. "
.ti -1c
.RI "void \fBdisplay_history\fP ()"
.br
.RI "Affiche l'historique des commandes\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HISTORY_FILE   'history\&.txt'"

.PP
Definition at line \fB9\fP of file \fBhistory\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void add_to_history (const char * command)"

.PP
Ajoute une commande à l'historique\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP Commande à ajouter\&. 
.RE
.PP

.PP
Definition at line \fB11\fP of file \fBhistory\&.c\fP\&..PP
.nf
11                                          {
12   if (!command) {
13       errno = EFAULT;
14       return;
15   }
16   
17   int fd = open(HISTORY_FILE, O_WRONLY | O_CREAT | O_APPEND, 0644);
18   if (fd == \-1) {
19     switch (errno) {
20         case EACCES: perror("add_to_history: Permission denied"); break;
21         case EISDIR: perror("add_to_history: Is a directory"); break;
22         case ENOENT: perror("add_to_history: No such file or directory"); break;
23         case EFAULT: perror("add_to_history: Bad address"); break;
24         default: perror("add_to_history: Failed to open history file"); break;
25     }
26     return;
27   }
28 
29   if (write(fd, command, strlen(command)) == \-1 || write(fd, "\\n", 1) == \-1) {
30         switch (errno) {
31             case EFAULT: perror("add_to_history: Bad address"); break;
32             default: perror("add_to_history: Fail to write to history file"); break;
33         }
34   }
35 
36   close(fd);
37 }
.fi

.SS "void display_history ()"

.PP
Affiche l'historique des commandes\&. 
.PP
Definition at line \fB39\fP of file \fBhistory\&.c\fP\&..PP
.nf
39                        {
40   FILE *file = fopen(HISTORY_FILE, "r");
41   if (!file) {
42     switch (errno) {
43         case EACCES: perror("display_history: Permission denied"); break;
44         case ENOENT: perror("display_history: No such file or directory"); break;
45         default: perror("display_history: Failed to open history file"); break;
46     }
47     return;
48   }
49 
50   char line[1024];
51   int line_number = 1;
52   while (fgets(line, sizeof(line), file)) {
53     printf("%d: %s", line_number++, line);
54   }
55 
56   fclose(file);
57 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Alizée et Vladimir minishell from the source code\&.
