.TH "Minishelln/include/parser.h" 3 "Version 1.0" "shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Minishelln/include/parser.h
.SH SYNOPSIS
.br
.PP
\fC#include 'typedef\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPARSER_H\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBparse_control_operators\fP (const char *input, \fBCommandNode\fP commands[])"
.br
.RI "Parse une chaîne de caractères en une liste de commandes\&. "
.ti -1c
.RI "char ** \fBparse_command\fP (const char *command)"
.br
.RI "Parse une chaîne de caractères en une liste d'arguments\&. "
.ti -1c
.RI "char ** \fBsplit_pipes\fP (const char *command)"
.br
.RI "Découpe une chaîne de caractères en fonction des pipes\&. "
.ti -1c
.RI "int \fBis_background_command\fP (char **args)"
.br
.RI "Vérifie si une commande est en arrière-plan\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PARSER_H"

.PP
Definition at line \fB3\fP of file \fBparser\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int is_background_command (char ** args)"

.PP
Vérifie si une commande est en arrière-plan\&. 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Tableau d'arguments de la commande\&. 
.RE
.PP
\fBReturns\fP
.RS 4
1 si la commande est en arrière-plan, 0 sinon\&. 
.RE
.PP

.PP
Definition at line \fB146\fP of file \fBparser\&.c\fP\&..PP
.nf
146                                        {
147   if (!args) {
148     errno = EFAULT;
149     return \-1;
150   }
151 
152   for (int i = 0; args[i]; i++) {
153     if (strcmp(args[i], "&") == 0) {
154       free(args[i]);
155       args[i] = NULL;
156       return 1;
157     }
158   }
159   return 0;
160 }
.fi

.SS "char ** parse_command (const char * command)"

.PP
Parse une chaîne de caractères en une liste d'arguments\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP Chaîne de caractères à parser\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Tableau d'arguments\&. 
.RE
.PP

.PP
Definition at line \fB60\fP of file \fBparser\&.c\fP\&..PP
.nf
60                                           {
61   if (!command) {
62     errno = EFAULT;
63     return NULL;
64   }
65 
66   char **args = malloc(MAX_ARGS * sizeof(char *));
67   if (!args) {
68     errno = ENOMEM;
69     return NULL;
70   }
71 
72   char *cmd_copy = strdup(command);
73   if (!cmd_copy) {
74     free(args);
75     errno = ENOMEM;
76     return NULL;
77   }
78 
79   char *token = strtok(cmd_copy, " ");
80   int i = 0;
81   while (token && i < MAX_ARGS \- 1) {
82     if (token[0] == '"' && token[strlen(token) \- 1] == '"') {
83       token[strlen(token) \- 1] = '\\0';
84       token++;
85     }
86     args[i] = strdup(token);
87     if (!args[i]) {
88       free(cmd_copy);
89       for (int j = 0; j < i; j++) {
90         free(args[j]);
91       }
92       free(args);
93       errno = ENOMEM;
94       return NULL;
95     }
96     i++;
97     token = strtok(NULL, " ");
98   }
99   args[i] = NULL;
100 
101   free(cmd_copy);
102   return args;
103 }
.fi

.SS "int parse_control_operators (const char * input, \fBCommandNode\fP commands[])"

.PP
Parse une chaîne de caractères en une liste de commandes\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP Chaîne de caractères à parser\&. 
.br
\fIcommands\fP Tableau de commandes\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Nombre de commandes\&. 
.RE
.PP

.PP
Definition at line \fB9\fP of file \fBparser\&.c\fP\&..PP
.nf
9                                                                        {
10   if (!input || !commands) {
11     errno = EFAULT;
12     return \-1;
13   }
14   
15   int count = 0;
16   const char *ptr = input;
17   char buffer[1024];
18   int buf_index = 0;
19 
20   while (*ptr && count < MAX_COMMANDS) {
21     // Reset du buffer
22     buf_index = 0;
23 
24     while (*ptr == ' ') {
25       ptr++;
26     }
27 
28     // Lis la commande jusqu'à trouver un opérateur de contrôle
29     while (*ptr && strncmp(ptr, "&&", 2) != 0 && strncmp(ptr, "||", 2) != 0) {
30       if (buf_index < (int)(sizeof(buffer) \- 1)) {
31         buffer[buf_index++] = *ptr;
32       }
33       ptr++;
34     }
35 
36     buffer[buf_index] = '\\0';
37     if (buf_index > 0) {
38       commands[count]\&.command = strdup(buffer);
39       if (!commands[count]\&.command) {
40         errno = ENOMEM;
41         return \-1;
42       }
43       commands[count]\&.type = CMD_NONE;
44       count++;
45     }
46 
47     // Détection de l'opérateur de contrôle
48     if (strncmp(ptr, "&&", 2) == 0) {
49       commands[count \- 1]\&.type = CMD_AND;
50       ptr += 2;
51     } else if (strncmp(ptr, "||", 2) == 0) {
52       commands[count \- 1]\&.type = CMD_OR;
53       ptr += 2;
54     }
55   }
56 
57   return count;
58 }
.fi

.SS "char ** split_pipes (const char * command)"

.PP
Découpe une chaîne de caractères en fonction des pipes\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP Chaîne de caractères à découper\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Tableau de commandes\&. 
.RE
.PP

.PP
Definition at line \fB105\fP of file \fBparser\&.c\fP\&..PP
.nf
105                                         {
106   if (!command) {
107     errno = EFAULT;
108     return NULL;
109   }
110 
111   char **segments = malloc(MAX_PIPE_SEGMENTS * sizeof(char *));
112   if (!segments) {
113     errno = ENOMEM;
114     return NULL;
115   }
116 
117   char *cmd_copy = strdup(command);
118   if (!cmd_copy) {
119     free(segments);
120     errno = ENOMEM;
121     return NULL;
122   }
123 
124   char *token = strtok(cmd_copy, "|");
125   int i = 0;
126   while (token && i < MAX_PIPE_SEGMENTS \- 1) {
127     segments[i] = strdup(token);
128     if (!segments[i]) {
129       free(cmd_copy);
130       for (int j = 0; j < i; j++) {
131         free(segments[j]);
132       }
133       free(segments);
134       errno = ENOMEM;
135       return NULL;
136     }
137     i++;
138     token = strtok(NULL, "|");
139   }
140   segments[i] = NULL;
141 
142   free(cmd_copy);
143   return segments;
144 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for shell from the source code\&.
