.TH "Minishelln/include/typedef.h" 3 "Version 1.0" "shell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Minishelln/include/typedef.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBCommandNode\fP"
.br
.RI "Structure représentant un noeud de commande\&. "
.ti -1c
.RI "struct \fBEnvVar\fP"
.br
.RI "Structure représentant une variable d'environnement\&. "
.ti -1c
.RI "struct \fBAlias\fP"
.br
.RI "Structure représentant un alias\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_ARGS\fP   128"
.br
.ti -1c
.RI "#define \fBMAX_ENV_VARS\fP   128"
.br
.ti -1c
.RI "#define \fBMAX_ALIASES\fP   64"
.br
.ti -1c
.RI "#define \fBMAX_PIPE_SEGMENTS\fP   16"
.br
.ti -1c
.RI "#define \fBMAX_COMMANDS\fP   3"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCommandType\fP { \fBCMD_NONE\fP, \fBCMD_AND\fP, \fBCMD_OR\fP }"
.br
.RI "Enumération des types de commandes logiques\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_ALIASES   64"

.PP
Definition at line \fB6\fP of file \fBtypedef\&.h\fP\&.
.SS "#define MAX_ARGS   128"

.PP
Definition at line \fB4\fP of file \fBtypedef\&.h\fP\&.
.SS "#define MAX_COMMANDS   3"

.PP
Definition at line \fB8\fP of file \fBtypedef\&.h\fP\&.
.SS "#define MAX_ENV_VARS   128"

.PP
Definition at line \fB5\fP of file \fBtypedef\&.h\fP\&.
.SS "#define MAX_PIPE_SEGMENTS   16"

.PP
Definition at line \fB7\fP of file \fBtypedef\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCommandType\fP"

.PP
Enumération des types de commandes logiques\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICMD_NONE \fP\fP
.TP
\fB\fICMD_AND \fP\fP
.TP
\fB\fICMD_OR \fP\fP
.PP
Definition at line \fB13\fP of file \fBtypedef\&.h\fP\&..PP
.nf
13 { CMD_NONE, CMD_AND, CMD_OR } CommandType;
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for shell from the source code\&.
